# Generated by Django 4.0.4 on 2022-04-28 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movierate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_title',
            new_name='movie_about',
        ),
    ]
